### PR TITLE
Thing can now have keys other than string

### LINKED ISSUE #89: Bug: Thing key only supports string value
The key portion of a given thing is a JSON element.

- `Thing(string table, string key)`
- `Thing<T>(string table, T key)`
- `ThingJson(string table, JsonElement key)`

## Thing
`Thing` accepts only alphanumeric values. It represents the most primitive usage. It is interpolated like so `mytable:mykey123`. This is handled as a `Thing<string>` during serialization.

## ThingJson
`ThingJson` allows interpolation using an arbitrary JSON element. Interpolation is performed as follows:

| Kind |  Interpolation |
|---|---|
| object | `mytable:{value: 1: arr: ["this", "is", "sparta"]}` |
| array | `mytable:["this", "is", "sparta"]` |
| string | `mytable:this_is_sparta` quotes are omitted |
| number |  `mytable:420` |
| ... | ...| 

## Thing`1
`Thing<T>` is a convenience type to allow easy modification. During serialization, the boxed object `key` is JSON serialized and the handling of `ThingJson` applies.

### PR DESCRIPTION
**Pull request by Du-z**
Thing can now take any object for the Key and will close #89.

Fixed some issues with some unicode characters not being considered to be a 'complex character'.

It also fixes some issues from changes in the nightly build. However there seems to be an issue with modify that I have not been able to figure out, @ProphetLamb you might be able to figure out what is going wrong there.

I had to disable a bunch of tests because of the following SurrealDB bug surrealdb/surrealdb#1364

### CODE REVIEW

**Comment by ProphetLamb** [comment]
I'll take a look at it, thanks

**Comment by ProphetLamb** [comment]
Might have to just always use JSON objects as keys. Even for primitives, such as integers and strings. The overhead for serialization  is pretty minimal in those cases

**Comment by Du-z** [comment]
@ProphetLamb Got all the tests to go green on my windows machine.

There is something weird with the `RestGuidQueryTests` in the `core 3.1` builds, I'm wondering if they go red on your machine too?

**Comment by Du-z** [comment]
On the other hand #97 just passed which is based off of this branch. 🤔

**Comment by ProphetLamb** [comment]
Maybe they fixed it in the meantime? I'll run the action again

**Comment by Du-z** [comment]
Looks like that did the trick!

**Review by ProphetLamb — APPROVED** [review]
Great, I was looking at it and wondering why it didn't work. Well because it already did work XD

Thanks a lot for the contribution. Cheers!

**Pull request merged**
