### PR TITLE
Solve nullability warnings for Thing

### PR DESCRIPTION
**Pull request by ProphetLamb**
The `Thing` ctor now handles null strings as an empty thing.

### CODE REVIEW

**Review by Du-z — COMMENTED** [review]
Looks, good, could you add a test for a null `Thing`?

**Review by Du-z — APPROVED** [review]

**Comment by ProphetLamb** [comment]
Right will do

**Comment by ProphetLamb** [comment]
Now the `default` value of Thing, is a valid struct and equivalent to `new(null)`. Structs are often only zeroed, but uninitialized.

**Comment by ProphetLamb** [comment]
Update the failing testcase in #108

**Review by Du-z — APPROVED** [review]

**Pull request merged**
