### PR TITLE
Setting up docs

### LINKED ISSUE #8: Feature: API Documentation and Examples
Yea that stuff no one wants to do. Some "Quick Start" examples are usually better than docs. But docs would be good aswell, maybe autogenerate markdown docs and then a static website from thereon?

### PR DESCRIPTION
**Pull request by AntoniosBarotsis**
Closes #8 

## Checklist

- [X] Host the XML code documentation on Github Pages
- [X] Add some "Getting Started" examples (installation, usage etc, showcase example folder)
- [X] Stylistic touches to the website
- [X] Add a "View Source" button (Optional)

For now you can check the website [here](https://antoniosbarotsis.github.io/Surreal.Net/) or serve from source with `mkdocs serve`.
You can install mkdocs with `pip install mkdocs-material` or check [here](https://squidfunk.github.io/mkdocs-material/getting-started/#installation).

For the stylistic changes, take a look [here](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/) and let me know if you want something/add it yourself :)

### CODE REVIEW

**Comment by ProphetLamb** [comment]
YES! Thank you sooo much. We really need those docs! I actually wrote a small getting started, so be sure to fetch upstream :3.

**Comment by AntoniosBarotsis** [comment]
I wonder if I should just make the action paste the contents of the README file into the landing page of the doc site 🤔

**Comment by ProphetLamb** [comment]
> I wonder if I should just make the action paste the contents of the README file into the landing page of the doc site thinking

That's a neat idea. We can always add more on top

**Comment by ProphetLamb** [comment]
Thought I wonder whether it is also possible to have source-link for the API reference section, similar to the source button in a rust crate: https://docs.rs/rand/latest/rand/

image

If that's not trivial, it's probably not worth the effort, but still interesting to look into :D

**Comment by AntoniosBarotsis** [comment]
I saw this being a thing in XmlDocMd although it wasn't working for some reason, I'll try adding that too (the path was a bit wrong so should be trivial)

**Comment by ProphetLamb** [comment]
@all-contibutors add @AntoniosBarotsis for docs

**Comment by ProphetLamb** [comment]
@all-contributors add @AntoniosBarotsis for docs

**Comment by AntoniosBarotsis** [comment]
Ok so, update on the "View Source" button, turns out XmlDocMd assumes that the file is titled the same as the class/interface present in it which works fine unless you have multiple per file.

For example

- [`DatabaseRest.cs`](https://github.com/ProphetLamb/Surreal.Net/blob/master/src/Driver/Rest/DatabaseRest.cs) works fine as the file contains just that one class
- [`Database.cs`](https://github.com/ProphetLamb/Surreal.Net/blob/master/src/Abstractions/Database.cs) does not as it generates `https://github.com/ProphetLamb/Surreal.Net/tree/master/src/Abstractions/IDatabase.cs` twice (it also does not consider generics in the name), once for `IDatabase<TResponse>` and another for `IDatabase`.

I don't think I can do anything about this but it might be worth refactoring the code such that only one entity is present per file to avoid this as the button itself is indeed useful.

I'll push the changes for now for testing purposes.

**Comment by ProphetLamb** [comment]
This line causes the issue: 
https://github.com/ejball/XmlDocMarkdown/blob/ec2c74e643cd4db80b1c9d86cbdad8835380cdb0/src/XmlDocMarkdown.Core/MarkdownGenerator.cs#L595

Here XmlDocMarkdown assumes that the filename can be derived from the (short) typename I'll fork the project and see if I can fix it

**Comment by ProphetLamb** [comment]
This snipped extracts the filenames containing each type from a dll pdb combo:
```csharp
using Mono.Cecil;
using Mono.Cecil.Cil;
using Mono.Cecil.Pdb;

IEnumerable<TypeFile> GetTypesFiles(string dir, string dllFile, string pdbFile) {
    DefaultAssemblyResolver asmResolver = new();
    asmResolver.AddSearchDirectory(dir);
    ReaderParameters parameters = new() { ReadSymbols = true};
    ModuleDefinition mod = ModuleDefinition.ReadModule(dllFile, parameters);
    AssemblyDefinition asm = mod.Assembly;
    
    PdbReaderProvider pdbReader = new();
    ISymbolReader symbols = pdbReader.GetSymbolReader(mod, pdbFile);
    foreach (TypeDefinition type in asm.MainModule.GetTypes()) {
        if (!type.HasMethods) {
            continue;
        }

        foreach (SequencePoint? seq in type.Methods
           .Select(method => symbols.Read(method))
           .Select(symbol => symbol.SequencePoints
               .Where(static seq => seq is not null).FirstOrDefault())
           .Where(seq => seq is not null)) {
            yield return new(type, seq.Document.Url);
        }
    }
}

string SourceAssemblyFolder = "/home/prophetlamb/repos/Surreal.Net/publish";
string SourceAssemblyFileName = "/home/prophetlamb/repos/Surreal.Net/publish/Json.dll";
string SourceSymbolsFileName = "/home/prophetlamb/repos/Surreal.Net/publish/Json.pdb";


var defs = GetTypesFiles(SourceAssemblyFolder, SourceAssemblyFileName, SourceSymbolsFileName).ToArray();
foreach (var def in defs) {
    Console.WriteLine(def.ToString());
}

record struct TypeFile(TypeDefinition type, string filepath);
```

Joke's on me an Interface declaration doesn't have any ECMA `SequencePoint`s because there is no method body and thus no file is found ^^

**Comment by AntoniosBarotsis** [comment]
So are you going to be putting that on your fork or how do we glue this together?

**Comment by ProphetLamb** [comment]
> So are you going to be putting that on your fork or how do we glue this together?

I'll make a seperate tool that generates a mapping csv.
The fork will then accept the csv as an argument.
The mapping is then queried for the filename.

**Comment by AntoniosBarotsis** [comment]
Alright! Let me know when that's ready then

**Comment by ProphetLamb** [comment]
So Ive made two tools, one that extracts sources from a nuget package using sourcelink information and a second one that creates a symbol mapping like so:
```json
[
  {
    "typename": "SurrealDB.Abstractions.IDatabase`1",
    "link": "https://raw.githubusercontent.com/ProphetLamb/Surreal.Net/9050c906117c795ca385fd52b75062771a2a8816/src/Abstractions/Database.cs",
    "start": 6,
    "end": 141
  },
  {
    "typename": "SurrealDB.Abstractions.IDatabase",
    "link": "https://raw.githubusercontent.com/ProphetLamb/Surreal.Net/9050c906117c795ca385fd52b75062771a2a8816/src/Abstractions/Database.cs",
    "start": 141,
    "end": 295
  }
]
```

Note that start and end are the lines where the type starts and ends in the file. I am publishing them in a sec

**Comment by ProphetLamb** [comment]
For a more detailed description, see: https://github.com/ejball/XmlDocMarkdown/pull/91#issuecomment-1256426259

**Comment by ProphetLamb** [comment]
[props](/src/Directory.Build.props)

**Comment by AntoniosBarotsis** [comment]
I'm a bit confused as to which files I should give as arguments to them.

The first one can be either a dll/pdb/exe which is fine but what's the `meta.json`?

What would you run for the Abstractions folder for example (both commands)?

**Comment by ProphetLamb** [comment]
I explained the arguments in the respective repos. `extract` takes a compilation or a pdb and **produces** a metadata file and extracts the source files to a directory (effectively the same as `git clone`, but with the correct version, and only relevant `*.cs` files).
`mapper` consumes **both** outputs and generates the JSON I mentioned above.
The JSON filepath can then be passed to the fork as the `--source` argument

**Comment by AntoniosBarotsis** [comment]
I only seem to have the pdb files in my debug folder but when I try to run extract I get the following:

```sh
# in Surreal.Net/src/Abstractions/bin/Debug/net60
$  extract Abstractions.pdb meta.json out
Unhandled exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Program.<<Main>$>g__ParseDocument|0_2(Ctx ctx, DocumentHandle documentHandle) in /_/src/Program.cs:line 79
   at Program.<<Main>$>g__ParseSourceLink|0_1(MetadataReader reader, String metadata, String output) in /_/src/Program.cs:line 54
   at Program.<<Main>$>g__Cmd|0_0(String input, String metadata, String output) in /_/src/Program.cs:line 31
   at Program.<Main>$(String[] args) in /_/src/Program.cs:line 10
   at Program.<Main>(String[] args)
```

**Comment by ProphetLamb** [comment]
I cannot reproduce the bug, I assume your firewall is not blocking the app?

[test.pdb.zip](https://github.com/ProphetLamb/Surreal.Net/files/9636582/test.pdb.zip)

Ensure version 1.0.3 is installed and try this assembly (which is the Abstractions.pdb created on my machine)

**Comment by AntoniosBarotsis** [comment]
Ok that's weird, it works fine for your file but it crashes on the one generated locally. It seems that I only generate the pdb files if I build with debug mode for some reason, publishing doesn't generate them

**Comment by ProphetLamb** [comment]
I pushed full debugging symbols, maybe there is some discrepancy between linux and windows (I am assuming you're using windows)

**Comment by AntoniosBarotsis** [comment]
I am indeed on windows, I pulled and I can now see the pdb files but I get the following

```sh
# for Surreal.Net\src\Abstractions\bin\Release\net60\Abstractions.pdb
# and Surreal.Net\publish\Abstractions.pdb
$ extract path/to/pdb meta.json out
Unhandled exception. System.BadImageFormatException: Invalid COR20 header signature.
   at System.Reflection.Metadata.MetadataReader.ReadMetadataHeader(BlobReader& memReader, String& versionString)
   at System.Reflection.Metadata.MetadataReader..ctor(Byte* metadata, Int32 length, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder, Object memoryOwner)
   at System.Reflection.Metadata.MetadataReaderProvider.GetMetadataReader(MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
   at Program.<<Main>$>g__Cmd|0_0(String input, String metadata, String output) in /_/src/Program.cs:line 22
   at Program.<Main>$(String[] args) in /_/src/Program.cs:line 10
   at Program.<Main>(String[] args)
```

**Comment by ProphetLamb** [comment]
Guessed so, in this case it means hat dotnet is generating windows pdb's not portable pdb's... https://github.com/dotnet/symreader-converter

**Comment by ProphetLamb** [comment]
> Should I wait for the change and update to the newer version when that's done or try to set it up locally?

I would advise using linux, or manually converting using the tool I linked for testing. The CI will use Debian in any case, so it'll work there. Alternatively, use the CI for testing ^^

Validating magic numbers and handling edgecases is not going to happen in the tool for a few days.... 404 motivation to deal with ECMA standard vs whatever the heck the windows impl is doing

**Comment by AntoniosBarotsis** [comment]
Would you mind taking this from here then? Going back and fourth with the pipeline would take a while if I can't test it locally easily xd.

Everything else should be fine once this works and you can optionally also see if you wan to make any stylistic changes.

**Comment by ProphetLamb** [comment]
Alright, can do that. I didnt want to take your project away :3
I'll make time for it some when tomorrow, if all goes well

In any case, thanks for your contribution!

**Comment by ProphetLamb** [comment]
I updated the documentation with the new github page, give it a shot :D

**Comment by AntoniosBarotsis** [comment]
I am getting  `Unable to construct heritage path. Unknown node type: Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax`, [logs](https://github.com/AntoniosBarotsis/Surreal.Net/actions/runs/3118663967/jobs/5058102740)

The script

```sh
# Last is Abstractions, Common, Configuration, Rest etc
last=${stuff[${#stuff[@]}-1]}
# Relative path to publish folder
path=./src/$val/bin/Release/net60/publish

extract $path/$last.pdb $last-meta.json src/
mapper $last-meta.json src/ $last-symbols.json
xmldocmd $path/$last.dll ./docs/src --source src/ --symbols $last-symbols.json
```

**Comment by AntoniosBarotsis** [comment]
Ah I just noticed I didnt sync my fork, let me do that first

**Comment by AntoniosBarotsis** [comment]
Seems to be working!

The only things to keep in mind are that the link will be moved from `https://antoniosbarotsis.github.io/Surreal.Net/` to something like `https://ProphetLamb.github.io/Surreal.Net/` and that if more projects are added in the future, the `projs` list should be updated!

**Comment by AntoniosBarotsis** [comment]
A bit unrelated but I think changing `ci.yml` to

```yml
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
```

would solve the `Resource not accessible by integration` error (I think the write perm is for the action to reply to this thread but not sure).

**Comment by AntoniosBarotsis** [comment]
I guess not

**Comment by AntoniosBarotsis** [comment]
Messed around with the workflow a bit but reverted all of that so just ignore 👍

**Comment by ProphetLamb** [comment]
Alrighty. Thanks a lot for the work! <3

**Pull request merged**
